In [1]:
import pandas as pd
import re
from langdetect import detect
from langdetect import DetectorFactory

DetectorFactory.seed = 0

data = pd.read_csv('cleaned_dataset.csv')
data.head(8)

   Rating                                            Reviews  Review Votes
0       5  I feel so LUCKY to have found this used (phone...           1.0
1       4  nice phone, nice up grade from my pantach revu...           0.0
2       5                                       Very pleased           0.0
3       4  It works good but it goes slow sometimes but i...           0.0
4       4  Great phone to replace my lost phone. The only...           0.0
5       1  I already had a phone with problems... I know ...           1.0
6       2  The charging port was loose. I got that solder...           0.0
7       2  Phone looks good but wouldn't stay charged, ha...           0.0

In [2]:
data.dropna(inplace=True)

In [3]:
sum(data['Review Votes'].isnull())

0

In [4]:
data.reset_index(inplace=True)

In [5]:
reference = data['Review Votes']>0
index = -1
for row in reference:
    index=index+1
    if not row:
        data.drop(index,inplace=True)
print('Program finished!')

Program finished!

In [6]:
data.reset_index(inplace=True)

In [7]:
index = -1
try:
    for review in data['Reviews']:
        index = index + 1
        if re.search(r'[A-Za-z]',review) is None:
            data.drop(index,inplace=True)
            continue
        elif re.search(r'^http.*$',review) is not None:
            data.drop(index,inplace=True)
            continue
        elif len(review.split())<=2:
            continue
        if detect(review)!='en':
            data.drop(index,inplace=True)
        if index%1000==0:
            print('Reached',index)
finally:
    print('last index:',index)

Reached 0
Reached 1000
Reached 2000
Reached 3000
Reached 4000
Reached 5000
Reached 6000
Reached 7000
Reached 8000
Reached 9000
Reached 10000
Reached 11000
Reached 13000
Reached 14000
Reached 15000
Reached 16000
Reached 17000
Reached 18000
Reached 19000
Reached 20000
Reached 21000
Reached 22000
Reached 23000
Reached 24000
Reached 25000
Reached 26000
Reached 27000
Reached 28000
Reached 29000
Reached 30000
Reached 31000
Reached 32000
Reached 33000
Reached 34000
Reached 35000
Reached 36000
Reached 37000
Reached 38000
Reached 39000
Reached 40000
Reached 41000
Reached 42000
Reached 43000
Reached 44000
Reached 45000
Reached 46000
Reached 47000
Reached 48000
Reached 49000
Reached 50000
Reached 51000
Reached 52000
Reached 53000
Reached 54000
Reached 55000
Reached 56000
Reached 57000
Reached 58000
Reached 59000
Reached 60000
Reached 61000
Reached 62000
Reached 63000
Reached 64000
Reached 65000
Reached 66000
Reached 67000
Reached 68000
Reached 69000
Reached 70000
Reached 71000
Reached 72000
Reached 73000
Reached 74000
Reached 75000
Reached 76000
Reached 77000
Reached 78000
Reached 79000
Reached 80000
Reached 81000
Reached 83000
Reached 84000
Reached 85000
Reached 86000
Reached 87000
Reached 88000
Reached 89000
Reached 90000
Reached 91000
Reached 92000
Reached 94000
Reached 96000
Reached 97000
Reached 99000
Reached 100000
Reached 103000
Reached 104000
Reached 105000
Reached 106000
Reached 107000
Reached 108000
Reached 109000
Reached 110000
Reached 111000
Reached 112000
Reached 113000
Reached 114000
Reached 115000
Reached 116000
Reached 117000
Reached 118000
Reached 119000
Reached 120000
Reached 121000
Reached 122000
Reached 123000
last index: 123019

In [12]:
data.head(50)

,level_0,index,Rating,Reviews,Review Votes
0,0,0,5,I feel so LUCKY to have found this used (phone...,1.0
1,5,5,1,I already had a phone with problems... I know ...,1.0
2,12,12,5,These guys are the best! I had a little situat...,2.0
3,13,13,1,I'm really disappointed about my phone and ser...,1.0
4,14,14,5,Ordered this phone as a replacement for the sa...,1.0
5,16,16,5,I was able to get the phone I previously owned...,6.0
6,18,18,4,I love the phone. It does everything I need an...,1.0
7,22,22,1,I purchased this phone in December as a christ...,19.0
8,52,52,5,Bought this as an alternative to a smart phone...,1.0
9,57,57,5,Used this unlocked GSM Nokia Asha 302 in the P...,1.0
10,67,67,5,Nokia is the brand that can be used in telepho...,1.0
11,68,68,4,"First off, let me say I've been a Nokia user s...",12.0
12,69,69,5,Nokia Asha 302 Unlocked GSM Phone with 3.2MP C...,13.0
13,70,70,5,This is a solidly-built unlocked phone that is...,17.0
15,72,72,5,"THIS CELLPHONE IS VERY EASY FOR USING, IT HAS ...",4.0
16,74,74,4,Freezes alot. But i bought primarily for playi...,1.0
17,76,76,2,Preface: This is not what would be considered ...,9.0
18,77,77,5,We just received the phone a few days ago. Put...,3.0
19,78,78,5,I bought this phone as a Christmas present for...,3.0
20,79,79,4,The Phone is pretty good. I am using it with a...,2.0
21,80,80,5,loved everything about it. also it looks like ...,1.0
22,81,81,5,THIS IS A SOLUTION IF YOU WANT YOU ARE LOOKING...,2.0
23,82,82,5,This phone in an excellent phone at a great pr...,1.0
24,83,83,3,Have problems setting correct time on Nokia As...,5.0
25,84,84,4,This is a good phone although it seems to have...,1.0
26,85,85,5,I've been a long time user of the iPhone. I fi...,2.0
27,86,86,5,"This phone, like all of Nokia's feature phones...",12.0
28,97,97,4,"This cell phone exceeded my expectations, it's...",1.0
29,98,98,4,"pros.. it works fine, its easy to use, not too...",1.0
30,99,99,5,I went through lots of reviews for different p...,1.0
31,105,105,3,"a pretty capable, durable texting phone, unloc...",2.0
32,108,108,5,"Excellent phone, for adults recommend. . Whats...",1.0
33,109,109,5,I have enjoyed my Nokia C3 phone for a few yea...,1.0
34,116,116,5,Exactly what I was expecting.thank you.,1.0
35,119,119,5,phone works great for the price although when ...,1.0
36,120,120,5,Keeping in mind that this is a sub $100 phone ...,16.0
37,121,121,5,Is a good product That I recomended it has all...,9.0
38,140,140,4,Its great for the price but I hate how you can...,1.0
39,141,141,5,When I got new Phone. I loved this phone. but ...,3.0
40,143,143,5,I bouht this phone for my 82 year old mother w...,1.0
41,144,144,5,like your ad...love it!,1.0
42,146,146,5,Have a family member who has ZERO interest in ...,1.0
43,148,148,2,does not work well with T-Mobile. T-Mobile clo...,1.0
44,149,149,5,Screen size is good and easy to read. Sound co...,1.0
45,150,150,5,This is like the 5th cellphone for my dad in l...,1.0
46,151,151,5,This is a really great phone. I am visually im...,1.0
47,152,152,1,More complicated than I expected. Terrible rec...,2.0
48,154,154,1,phone reception poor with incoming calls,1.0
49,155,155,4,Nice phone. Easy to read screen. I am a senior...,6.0
50,156,156,5,The sleek design and easy of use is what makes...,3.0

In [13]:
data.reset_index(inplace=True)

ValueError: cannot insert level_0, already exists

In [14]:
data.to_csv('final_dataset.csv',index=False)